is_dev: true # if true than config would not ask env variables for credentials
server:
  host: 0.0.0.0
  port: 8000
  timeout:
    write: 20
    read: 15
sqldatabase:
  driver: postgres
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: db
  connection_limit: 10
redis:
  port: 6379
  password:
  address: 0.0.0.0
  db: 0
